swagger: "2.0"
info:
  description: "Este es la Documentacion del ApiRest para el Sistema de Control de Cirugias"
  version: "1.0.0"
  title: "Sistema de Control de Cirugias"
  contact:
    email: "g3tallerdesistemas@gmail.com"
# schemes:
# - "http"
paths:
  /api/auth/login:
    post:
      tags:
      - "Autentificacion"
      summary: "Ingresar al sistema"
      description: "Ingresar al sistema"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
              format: "email"
            password:
              type: "string"
              format: "varchar"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              access_token:
                type: "string"
              token_type:
                type: "string"
              expires_at:
                type: "string"
              message:
                type: "string"
        400:
          description: Page Not Found
  /api/auth/signup/activate/token:
    get:
      tags:
      - "Autentificacion"
      summary: "Activa el usuario"
      description: "Activa el usuario"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        400:
          description: Page Not Found
  /api/auth/sigup:
    post:
      tags:
      - "Autentificacion"
      summary: "Ingresar al sistema"
      description: "Ingresar al sistema"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            name:
              type: "string"
              format: "varchar"
            email:
              type: "string"
              format: "varchar"
            password:
              type: "string"
              format: "varchar"
            password_confirmation:
              type: "string"
              format: "varchar"
            id_rol:
              type: "number"
              format: "integer"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        400:
          description: Page Not Found
  /api/auth/logout:
    get:
      tags:
      - "Autentificacion"
      summary: "Salir del sistema"
      description: "Salir del sistema"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        400:
          description: Page Not Found
  /api/auth/user:
    get:
      tags:
      - "Autentificacion"
      summary: "informacion de usuario"
      description: "informacion de usuario"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              id:
                type: "number"
              name:
                type: "string"
              email:
                type: "string"
              active:
                type: "number"
              created_at:
                type: "string"
              updated_at:
                type: "string"
              deleted_at:
                type: "string"
              id_rol:
                type: "number"
              id_user:
                type: "number"
        400:
          description: Page Not Found
  /api/userCreator:
    post:
      tags:
      - "Usuarios"
      summary: "Muestra todos los usuarios creados por el usuario"
      description: "Muestra todos los usuarios creados por el usuario"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              id:
                type: "number"
              name:
                type: "string"
              email:
                type: "string"
              active:
                type: "number"
              created_at:
                type: "string"
              updated_at:
                type: "string"
              deleted_at:
                type: "string"
              id_rol:
                type: "number"
              id_user:
                type: "number"
        400:
          description: Page Not Found
  /api/user/id:
    get:
      tags:
      - "Usuarios"
      summary: "Muestra el detalle del usuario"
      description: "Muestra el detalle del usuario"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              id:
                type: "number"
              name:
                type: "string"
              email:
                type: "string"
              active:
                type: "number"
              created_at:
                type: "string"
              updated_at:
                type: "string"
              deleted_at:
                type: "string"
              id_rol:
                type: "number"
              id_user:
                type: "number"
        400:
          description: Page Not Found
  /(Update)/api/user/id:
    put:
      tags:
      - "Usuarios"
      summary: "Modificar un usuario"
      description: "Ingresar al sistema"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            name:
              type: "string"
              format: "varchar"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        400:
          description: Page Not Found
  /api/cirugia:
    post:
      tags:
      - "Cirugia"
      summary: "Crea una cirugia"
      description: "Crea una cirugia"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            id_paciente:
              type: "number"
            id_sala:
              type: "number"
            fechaIngreso:
              type: "string"
            fechaSalida:
              type: "string"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        400:
          description: Page Not Found
  /(Update)/api/cirugia/id:
    put:
      tags:
      - "Cirugia"
      summary: "Modifica una cirugia"
      description: "Modifica una cirugia"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            id_paciente:
              type: "number"
            id_sala:
              type: "number"
            fechaIngreso:
              type: "string"
            fechaSalida:
              type: "string"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        400:
          description: Page Not Found
  /api/cirugia/getCirugia:
    post:
      tags:
      - "Cirugia"
      summary: "Muestra todas las cirugia"
      description: "Muestra todas las cirugias"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              id:
                type: "number"
              id_paciente:
                type: "number"
              id_sala:
                type: "number"
              fechaIngreso:
                type: "string"
              fechaSalida:
                type: "string"
        400:
          description: Page Not Found
  /api/cirugia/id:
    post:
      tags:
      - "Cirugia"
      summary: "Muestra detalle de cirugia"
      description: "Muestra detalle de cirugia"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              id:
                type: "number"
              id_paciente:
                type: "number"
              id_sala:
                type: "number"
              fechaIngreso:
                type: "string"
              fechaSalida:
                type: "string"
        400:
          description: Page Not Found
  /api/salas:
    get:
      tags:
      - "Salas"
      summary: "Muestra todas las salas"
      description: "Muestra todas las salas"
      responses:
        200:
          description: Succses
          schema:
            type: "object"
            properties:
              id:
                type: "number"
              nombre:
                type: "string"
              descripcion:
                type: "string"
        400:
          description: Page Not Found
  
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /mateomen1996/Proyecto/1.0.0
# schemes:
#  - http
# Added by API Auto Mocking Plugin
schemes:
 - https
 - http