---
swagger: "2.0"
info:
  description: "Este es la Documentacion del ApiRest para el Sistema de Control de\
    \ Cirugias"
  version: "1.0.0"
  title: "Sistema de Control de Cirugias"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://181.188.163.198:8000/api"
host: "Cirugias"
basePath: "/v1"
tags:
- name: "Usuarios"
  description: "Login y Creacion de token"
  externalDocs:
    description: ""
    url: "http://181.188.163.198:8000/api/"
- name: "Personas"
  description: "AVM de los Pacientes"
  externalDocs:
    description: ""
    url: "http://181.188.163.198:8000/api/"
schemes:
- "https"
- "http"
paths:
  /api/auth/login:
    post:
      tags:
      - "Usuarios"
      summary: "Ingreso al sistema"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "correo"
        in: "query"
        description: "Correo electronico"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "La Contraseña del usuario"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalido correo o Contraseña incorrecta"
      x-swagger-router-controller: "Usuarios"
  /api/auth/logout:
    get:
      tags:
      - "Usuarios"
      summary: "Cerrado de Session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "Operacion exitosa"
      x-swagger-router-controller: "Usuarios"
  /api/auth/signup:
    post:
      tags:
      - "Usuarios"
      summary: "Creacion de Usuarios"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "El Usuario cierra la sesion"
        required: true
        schema:
          $ref: "#/definitions/DatosUsuario"
      responses:
        "201":
          description: "Usuario Creado Exitosamente"
        "401":
          description: "No Autorizado"
      x-swagger-router-controller: "Usuarios"
  /pet/auth/signup/activate/{token}:
    get:
      tags:
      - "Usuarios"
      summary: "Activacion del la Cuenta Correo electronico"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "token"
        in: "path"
        description: "Token"
        required: true
        type: "string"
      responses:
        "201":
          description: "Confirmacion de correo Exitoso"
        "404":
          description: "El token de Activacion es invalido"
      x-swagger-router-controller: "Usuarios"
  /api/auth/user:
    get:
      tags:
      - "Usuarios"
      summary: "Obtener datos del Usuario por token"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "token"
        in: "path"
        description: "Token"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/UsuarioRegistro"
        "404":
          description: "El token inexistente"
      x-swagger-router-controller: "Usuarios"
  /api/rol:
    get:
      tags:
      - "Usuarios"
      summary: "Muestra lo diferentes roles de Usuarios"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Solicita los roles existentes"
        required: true
        schema:
          $ref: "#/definitions/Rol"
      responses:
        "201":
          description: "Usuario Creado Exitosamente"
        "401":
          description: "No Autorizado"
      x-swagger-router-controller: "Usuarios"
  /api/user:
    get:
      tags:
      - "Usuarios"
      summary: "Muestra todos los usuarios que creaste"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Solicita todos los usuarios que el creo"
        required: true
        schema:
          $ref: "#/definitions/UsuarioRegistro"
      responses:
        "201":
          description: "Proceso Correcto"
        "401":
          description: "No Autorizado"
      x-swagger-router-controller: "Usuarios"
  /api/user1/{id}:
    put:
      tags:
      - "Usuarios"
      summary: "Actualizacion del usuario"
      description: ""
      operationId: "updateUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/UsuarioUP"
      responses:
        "201":
          description: "Usuario Actulizado Correctamente"
        "400":
          description: "no autorizado"
        "404":
          description: "Usuario no encontrado"
      x-swagger-router-controller: "Usuarios"
  /api/user/{id}:
    get:
      tags:
      - "Usuarios"
      summary: "Muestra todos los usuarios en el login"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id del usuario a mostrar datos"
        required: true
        type: "string"
      - name: "token"
        in: "path"
        description: "Token"
        required: true
        type: "string"
      responses:
        "200":
          description: "Operacion exitosa"
          schema:
            $ref: "#/definitions/UsuarioRegistro"
        "404":
          description: "Usuario inexistente"
      x-swagger-router-controller: "Usuarios"
  /api/userCreator:
    get:
      tags:
      - "Usuarios"
      summary: "Muestra informacion detallada de un usuario"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "token"
        in: "path"
        description: "Token"
        required: true
        type: "string"
      responses:
        "200":
          description: "operacion exitosa"
          schema:
            $ref: "#/definitions/UsuarioRegistro"
        "404":
          description: "Usuario inexistente"
      x-swagger-router-controller: "Usuarios"
definitions:
  Rol:
    type: "object"
    properties:
      rol:
        type: "integer"
        format: "int64"
    example:
      rol: 0
  DatosUsuario:
    type: "object"
    properties:
      name:
        type: "string"
        format: "varchar"
      email:
        type: "string"
        format: "varchar"
      passwors:
        type: "string"
        format: "varchar"
      confirm_password:
        type: "string"
        format: "varchar"
    xml:
      name: "Usuario"
    example:
      passwors: "passwors"
      name: "name"
      email: "email"
      confirm_password: "confirm_password"
  UsuarioUP:
    type: "object"
    properties:
      name:
        type: "string"
        format: "varchar"
    xml:
      name: "UsuarioUP"
  UsuarioRegistro:
    type: "object"
    properties:
      name:
        type: "string"
        format: "varchar"
      email:
        type: "string"
        format: "varchar"
      passwors:
        type: "string"
        format: "varchar"
      activation_token:
        type: "string"
        format: "varchar"
      id_rol:
        type: "integer"
        format: "int64"
      id_user:
        type: "integer"
        format: "int64"
    xml:
      name: "Usuario"
    example:
      activation_token: "activation_token"
      id_rol: 0
      passwors: "passwors"
      name: "name"
      id_user: 6
      email: "email"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
